<?php
/**
 * Serve a stored document to a signed-in admin.
 *
 * Files in assets/documents/ are denied by .htaccess, so this is the only way
 * to read one. That is deliberate: supplier agreements, staff training records
 * and inspection reports are the shop's business, and a filename is easy to
 * guess.
 *
 *   ?id=12          view it in the browser (a PDF opens in the viewer)
 *   ?id=12&dl=1     download it
 */

require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/_permissions.php';
adminRequire('documents');

require_once __DIR__ . '/../includes/documents.php';

$id = (int)($_GET['id'] ?? 0);
if ($id <= 0) {
    http_response_code(400);
    exit('No document asked for.');
}

if (!cbDocReady($pdo)) {
    http_response_code(503);
    exit('The documents area has not been set up on this server yet. Run the database update.');
}

$st = $pdo->prepare("SELECT * FROM documents WHERE id = :id");
$st->execute(['id' => $id]);
$doc = $st->fetch(PDO::FETCH_ASSOC);

if (!$doc) {
    http_response_code(404);
    exit('That document is not here.');
}

// basename() and a realpath check, belt and braces. stored_name is generated by
// the upload handler and should never contain a path, but this file streams
// whatever it is given — so it verifies the resolved path is genuinely inside
// the documents directory before opening anything.
$dir  = realpath(cbDocDir());
$path = realpath($dir . '/' . basename((string)$doc['stored_name']));

if ($dir === false || $path === false || !str_starts_with($path, $dir . DIRECTORY_SEPARATOR) || !is_file($path)) {
    http_response_code(404);
    error_log('Document row ' . $id . ' points at a file that is not in the documents folder.');
    exit('That file is missing. It may have been removed from the server.');
}

// The download name is the ORIGINAL one the owner recognises, not the generated
// storage name. Quotes and newlines are stripped: a filename is user input and
// this goes into a header.
$niceName = preg_replace('/[^A-Za-z0-9 ._-]/', '', (string)$doc['original_name']);
if ($niceName === '' || $niceName === null) { $niceName = 'document'; }

$disposition = !empty($_GET['dl']) ? 'attachment' : 'inline';

header('Content-Type: ' . $doc['mime']);
header('Content-Length: ' . filesize($path));
header('Content-Disposition: ' . $disposition . '; filename="' . $niceName . '"');
// Never let a shared cache hold a copy of an internal document.
header('Cache-Control: private, no-store');
header('X-Content-Type-Options: nosniff');

readfile($path);
